### ISSUE TITLE
v1.3.3 results in an error

### ISSUE THREAD

**Issue by runmad** [bugsnag/bugsnag-dsym-upload#21]
### Expected behavior
With v1.3.2 and the following setup uploading to Bugsnag worked well:

```ruby
lane :refresh_dsyms do
  download_dsyms(version: "latest")
  upload_symbols_to_bugsnag
  clean_build_artifacts
end
```

Running `fastlane action upload_symbols_to_bugsnag` outputs the correct default locations for all dsyms.

### Observed behavior
It no longer works. Instead it results in the following error: 

```ruby
------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'refresh_dsyms' 🚀
----------------------------
--- Step: download_dsyms ---
----------------------------
To not be asked about this value, you can specify it using 'username'
Your Apple ID Username for App Store Connect: email@email.com
Login to App Store Connect (email@email.com)
Login successful
Looking for latest version...
Looking for dSYM files for com.runemadsen.myapp v1.0.0 (100)
🔑  Successfully downloaded dSYM file for 1.0.0 - 100 to 'com.runemadsen.myapp-1.0.0-100.dSYM.zip'
---------------------------------------
--- Step: upload_symbols_to_bugsnag ---
---------------------------------------
+------------------+-------------------------------------------------------------------------------------+
|                                              Lane Context                                              |
+------------------+-------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM | ios                                                                                 |
| PLATFORM_NAME    |                                                                                     |
| LANE_NAME        | refresh_dsyms                                                                       |
| DSYM_PATHS       | ["/Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.z  |
|                  | ip"]                                                                                |
+------------------+-------------------------------------------------------------------------------------+
Failed uploading /Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.zip
fastlane finished with errors

[!] Failed uploading /Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.zip
```
Here's a more verbose version:

```ruby
INFO [2018-07-14 17:56:47.41]: 🔑  Successfully downloaded dSYM file for 1.0.0 - 100 to 'com.runemadsen.myapp-1.0.0-100.dSYM.zip'
DEBUG [2018-07-14 17:56:47.41]: Found train: 0.9.8, comparing to supplied version: 1.0.0
DEBUG [2018-07-14 17:56:47.41]: Version 1.0.0 doesn't match: 0.9.8
INFO [2018-07-14 17:56:47.41]: ---------------------------------------
INFO [2018-07-14 17:56:47.41]: --- Step: upload_symbols_to_bugsnag ---
INFO [2018-07-14 17:56:47.41]: ---------------------------------------
WARN [2018-07-14 17:56:47.42]: Lane Context:
INFO [2018-07-14 17:56:47.42]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"refresh_dsyms", :DSYM_PATHS=>["/Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.zip"]}
ERROR [2018-07-14 17:56:47.42]: Failed uploading /Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.zip
ERROR [2018-07-14 17:56:47.42]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/runemadsen/.gem/ruby/2.5.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Failed uploading /Users/runemadsen/Development/myapp-ios/com.runemadsen.myapp-1.0.0-100.dSYM.zip
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-plugin-bugsnag-1.3.3/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb:16:in `block in run'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-plugin-bugsnag-1.3.3/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb:9:in `each'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-plugin-bugsnag-1.3.3/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb:9:in `run'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:24:in `block in parsing_binding'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/runemadsen/.gem/ruby/2.5.0/gems/fastlane-2.99.1/bin/fastlane:20:in `<top (required)>'
  /Users/runemadsen/.gem/ruby/2.5.0/bin/fastlane:23:in `load'
  /Users/runemadsen/.gem/ruby/2.5.0/bin/fastlane:23:in `<top (required)>'
```

### Steps to reproduce
See above. Reproducible every time on 1.3.3, same command works fine on 1.3.2.

### Version
v1.3.3

### Additional information
Fastlane version is 2.99.1

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by kattrali** [comment]
Thanks for the report, @runmad. Looking into it.

**Comment by andreyslyusar** [comment]
I think we have some similar issue 
```
[18:25:01]: undefined method `each' for #<String:0x007fd493bd2a30>
[18:25:01]: You passed invalid parameters to 'upload_symbols_to_bugsnag'.
[18:25:01]: Check out the error below and available options by running `fastlane action upload_symbols_to_bugsnag`
```

```
  lane :refresh_dsyms do
    download_dsyms(
      app_identifier: get_app_identifier,
      version: get_app_version,
      build_number: gitlab_ci_build_id,
    )
    upload_symbols_to_bugsnag
  end
```

**Comment by andreyslyusar** [comment]
Latest v1.3.4 failed with the same error.

**Comment by kattrali** [comment]
@andreyslyusar Did you run `bundle exec fastlane update_plugins`? If so can you paste the new error output and contents of `fastlane/Pluginfile` and `Gemfile.lock`? I can reproduce this issue with 1.3.3 but not 1.3.4.

**Comment by runmad** [comment]
It’s been resolved for me.

**Comment by andreyslyusar** [comment]
Yes Gemfile.lock
```
    fastlane-plugin-bugsnag (1.3.4)
      git
      xml-simple
```

**Comment by kattrali** [comment]
@runmad Thanks for the confirmation. 👍 

@andreyslyusar Are you running fastlane using `bundle exec fastlane [lane]`? If not its possible that a previous version is being picked up. What is the contents of the stacktrace if you run `bundle exec fastlane [lane] --verbose`?

**Comment by andreyslyusar** [comment]
@kattrali I am running using `bundle exec`, I will add `--verbose` flag with next build.

**Comment by andreyslyusar** [comment]
@kattrali Below you can find output with `--verbose` flag 

```
ERROR [2018-07-20 16:56:23.52]: undefined method `each' for #<String:0x007feeff44ec38>
ERROR [2018-07-20 16:56:23.53]: You passed invalid parameters to 'upload_symbols_to_bugsnag'.
ERROR [2018-07-20 16:56:23.53]: Check out the error below and available options by running `fastlane action upload_symbols_to_bugsnag`
WARN [2018-07-20 16:56:23.53]: Lane Context:
INFO [2018-07-20 16:56:23.53]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy", :BUILD_NUMBER=>"812", :GET_INFO_PLIST_VALUE_CUSTOM_VALUE=>"***************", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"***************"=>"match AppStore ***************"}, :IPA_OUTPUT_PATH=>"***************/packages/mobile/ios/fastlane/build/app.ipa", :DSYM_OUTPUT_PATH=>"***************/packages/mobile/ios/fastlane/build/app.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/maintenance/Library/Developer/Xcode/Archives/2018-07-20/app 2018-07-20 16.33.23.xcarchive", :DSYM_PATHS=>["***************/packages/mobile/ios/***************-3.0.0-812.dSYM.zip"]}
ERROR [2018-07-20 16:56:23.53]: Invalid default value for dsym_path, doesn't match verify_block
```

```
DEBUG [2018-07-20 16:56:23.55]: All plugins are up to date
ERROR [2018-07-20 16:56:23.55]: fastlane finished with errors
DEBUG [2018-07-20 16:56:23.55]: All plugins are up to date
```


```
bundler: failed to load command: fastlane (/Users/maintenance/.rbenv/versions/2.2.3/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Invalid default value for dsym_path, doesn't match verify_block
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:151:in `rescue in block in verify_default_value_matches_verify_block'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:145:in `block in verify_default_value_matches_verify_block'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:142:in `each'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:142:in `verify_default_value_matches_verify_block'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:69:in `initialize'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/configuration_helper.rb:8:in `parse'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:236:in `block (2 levels) in execute_action'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:77:in `block (2 levels) in parsing_binding'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:66:in `block (2 levels) in parsing_binding'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/maintenance/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/bin/fastlane:20:in `<top (required)>'
  /Users/maintenance/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
  /Users/maintenance/.rbenv/versions/2.2.3/bin/fastlane:23:in `<top (required)>'
```

**Comment by fractalwrench** [comment]
@andreyslyusar sorry to hear you're still encountering issues with bugsnag-dsym-upload trouble - I think it would be best to follow #24, and we'll investigate further.

**Comment by EmDee** [comment]
Any updates on this issue? We're seeing the exact same behavior. #24's workaround seems to be working.

**Comment by Cawllec** [comment]
Hi @EmDee, we're looking at getting an update released soon, I'll find out whether this issue is fixed, and raise it if it isn't.
